library(car)
library(geiger)
library(nlme)
potato=(read.csv("potato_accessions.csv", header = TRUE, row.names=1))
modelg = lm (potato$total.glycoalkaloid ~ potato$landrace.2x+potato$landrace.4x)
models = lm (potato$starch.content ~ potato$landrace.2x+potato$landrace.4x)
model1 = lm (potato$mean.lesion ~ potato$landrace.2x+potato$landrace.4x)
model3 = lm (potato$flower.color ~ potato$landrace.2x+potato$landrace.4x)
model4 = lm (potato$Collection.Site ~ potato$landrace.2x+potato$landrace.4x)
model5 = lm (potato$habit ~ potato$landrace.2x+potato$landrace.4x)
model6 = lm (potato$Cultivation.Zone ~ potato$landrace.2x+potato$landrace.4x)
model7 = lm (potato$stolon.type ~ potato$landrace.2x+potato$landrace.4x)
model8 = lm (potato$circadian.average ~ potato$landrace.2x+potato$landrace.4x)
model9 = lm (potato$Elevation..MASL. ~ potato$landrace.2x+potato$landrace.4x)
model2 = lm (potato$ratio.of.diploids ~ potato$landrace.2x+potato$landrace.4x)
avPlots(modelg)
avPlots(models)
avPlots(model1)
avPlots(model2)
avPlots(model3)
avPlots(model4)
avPlots(model5)
avPlots(model6)
avPlots(model7)
avPlots(model8)
avPlots(model9)
##### wild potato phylogeny
attempt = read.newick("attempt.txt")
plot(attempt)
tip = c("S_etuberosum", "S_chomatophium", "S_megistacrolobum", "S_verrucosum", "S_boliviense", "S_infundibuliforme", "S_candolleanum", "S_spegazzinii", "S_gourlayi", "S_vernei", "S_microdontum", "S_okadae")
attempt1= drop.tip(attempt, tip)
root1 = force.ultrametric(attempt1)
data1 = read.csv("data1.csv")
tip1 = c("S_etuberosum", "S_chomatophium", "S_ehrenbergii", "S_raphanifolium", "S_medians", "S_leptophyes", "S_brevicaule", "S_boliviense", "S_candolleanum", "S_okadae", "S_kurtzianum")
attempt2 = drop.tip(attempt, tip1)
data2 = read.csv("data2.csv")
potato_tree = reroot(attempt,1)
landrace2 = data1$landrace.2x
landrace4 = data1$landrace.4x
glyco = data1$total.glycoalkaloid
landrace2 = data2$landrace.2x
landrace4 = data2$landrace.4x
starch = data2$starch.content
pglsModel3<-gls(landrace2*landrace4~glyco, correlation=corBrownian(phy=root1), method="ML")
anova(pglsModel3)
pglsModel2<-gls(landrace2*landrace4~starch, correlation=corBrownian(phy=attempt2), method="ML")
anova(pglsModel2)

res = resid(pglsModel3)
qqnorm(res)
qqline(res)
res2 = resid(pglsModel2)
qqnorm(res2)
qqline(res2)